### ISSUE TITLE
JS crash in rwt.event.DomEvent.isAltGrPressed() while drag'n'drop

### ISSUE THREAD

**Issue by hendeltom** [eclipse-rap/org.eclipse.rap#131]
If you start a drag'n'drop operation unintentionally and release the mouse more or less immediately after D'n'D was recognized then you may get a crash because the code fakes a mouse event ("mouseout") which which confuses a `rwt.event.DomEvent` instance; in `rwt.event.DomEvent.isAltGrPressed()` the code calls `this.getDomEvent().getModifierState("AltGraph");` but the actual (faked) DOM event instance is not a real MouseEvent instance and does not have the method "getModifierState()".
The fake event is created in `rwt.remote.DNDSupport._dragStartHandler()`:
```js
// fix for bug 296348
rwt.widgets.util.WidgetUtil._fakeMouseEvent( this._currentTargetElement, "mouseout" );
```
This creates an instance of `rwt.event.MouseEvent` which actually does not have the method "getModifierState()" while the JS MouseEvent does.
So the solution could be to add this method to `rwt.event.MouseEvent`.

The callstack is:
```
TypeError: this.getDomEvent(...).getModifierState is not a function
    at Object.isAltGrPressed (rap-client.js:16025:33)
    at setStateMask (rap-client.js:67400:36)
    at initMouseEvent (rap-client.js:67336:3)
    at new rwt.scripting.EventProxy (rap-client.js:67106:7)
    at rap-client.js:66781:26
    at Object._dispatchEvent (rap-client.js:3855:18)
    at Object.dispatchEvent (rap-client.js:3796:12)
    at Object._fakeMouseEvent (rap-client.js:7051:16)
    at rwt.remote.DNDSupport._dragStartHandler (rap-client.js:44177:37)
```

**Comment by hendeltom** [comment]
After further investigation while searching for a workaround I came to the conclusion that the problem should be fixed in `rwt.widgets.util.WidgetUtil._fakeMouseEvent()` 
```js
        var domEvent = {
          "type" : type,
          "target" : domTarget,
          "button" : 0,
          "wheelData" : 0,
          "detail" : 0,
          "pageX" : 0,
          "pageY" : 0,
          "clientX" : 0,
          "clientY" : 0,
          "screenX" : 0,
          "screenY" : 0,
          "shiftKey" : false,
          "ctrlKey" : false,
          "altKey" : false,
          "metaKey" : false,
          "preventDefault" : function(){}
        };
        var event = new rwt.event.MouseEvent( type,
                                              domEvent,
                                              domTarget,
                                              target,
                                              originalTarget,
                                              null );
```
The object `domEvent` should get `"getModifierState" : function() { return false; }`.
