### ISSUE TITLE
RWT 4 issue with 'contextDirectory' using Jetty embedded

### ISSUE THREAD

**Issue by brotenet** [eclipse-rap/org.eclipse.rap#248]
Hello :)

I am trying to get an RWT 4.0 (rap-4.0.0-R-20240904-0717) application up and running using the Jetty (12.0.12) dependencies that are included in the RWT 4.0 Release archive in **embedded mode** and I keep getting the following error in 'server.start()':
```
java.lang.NullPointerException: The parameter 'contextDirectory' must not be null.
``` 
..which is raised by the ParamCheck.java class.

This is the server initiation code:
```java
private static void testBasicServer() throws Exception {
		Server server = new Server(8080);
        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setTempDirectory(new File("/tmp/" + UUID.randomUUID().toString())); //Create a unique temp directory
        context.newResource(new URI(context.getTempDirectory().getCanonicalPath())); //Set the temp directory as the resource path 
        context.setContextPath("/");
        context.setInitParameter("org.eclipse.rap.applicationConfiguration", "tests.HelloWorldConfiguration");
        context.addEventListener(new RWTServletContextListener());
        ServletHolder rwtServletHolder = new ServletHolder(new RWTServlet());
        context.addServlet(rwtServletHolder, "/hello");
        server.setHandler(context);
        server.start(); //This is where the code breaks
        server.join();
	}
``` 

This is the full exception trace:
```
java.lang.NullPointerException: The parameter 'contextDirectory' must not be null.
	at org.eclipse.rap.rwt.internal.util.ParamCheck.notNull(ParamCheck.java:29)
	at org.eclipse.rap.rwt.internal.resources.ResourceDirectory.configure(ResourceDirectory.java:27)
	at org.eclipse.rap.rwt.internal.application.ApplicationContextImpl.doActivate(ApplicationContextImpl.java:372)
	at org.eclipse.rap.rwt.internal.application.ApplicationContextImpl.activate(ApplicationContextImpl.java:244)
	at org.eclipse.rap.rwt.application.ApplicationRunner.start(ApplicationRunner.java:80)
	at org.eclipse.rap.rwt.engine.RWTServletContextListener.contextInitialized(RWTServletContextListener.java:51)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:1591)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.contextInitialized(ServletContextHandler.java:497)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.initialize(ServletHandler.java:670)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.startContext(ServletContextHandler.java:1325)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1047)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1446)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1044)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:624)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:120)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:491)
	at org.eclipse.jetty.server.Server.doStart(Server.java:565)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at tests.Testing.testBasicServer(Testing.java:39)
	at tests.Testing.main(Testing.java:20)
``` 

_Please note that the aforementioned code used to work perfectly with older versions of RWT (e.g. 3.4 and older)_

I am most probably missing something here... but I really cannot find what it is.
Any suggestion on how to fix this would be greatly appreciated.

![ksnip_20241114-064943](https://github.com/user-attachments/assets/8fe6b96a-b4ae-43a2-b6a0-814be84bb4e6)

**Comment by brotenet** [comment]
Issue fixed.
Here is the code I used for anyone that might find it helpful:

	private static Server newServer(Class<?> application_class, String api_servlet_class_name, String public_resources_context, String public_resources_dir) throws Exception {
		String runtime_resources_path = System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + UUID.randomUUID().toString();
		try { Files.createDirectories(Paths.get(runtime_resources_path)); } catch (IOException exception) { exception.printStackTrace(); }
		Server server = new Server();
		ServletContextHandler handler = new ServletContextHandler(ServletContextHandler.SESSIONS);
		handler.setContextPath("/");
		handler.setBaseResource((new PathResourceFactory()).newResource(Paths.get(runtime_resources_path)));
		handler.setInitParameter("org.eclipse.rap.applicationConfiguration", application_class.getCanonicalName());
		handler.addEventListener(new RWTServletContextListener());
		handler.addServlet(RWTServlet.class.getName(), "/");
        handler.addServlet(DefaultServlet.class, "/rwt-resources/*");
        if(public_resources_dir != null) {
        	ServletHolder publicHolder = new ServletHolder("public", DefaultServlet.class);
	        publicHolder.setInitParameter("resourceBase",public_resources_dir);
	        publicHolder.setInitParameter("dirAllowed","true");
	        publicHolder.setInitParameter("pathInfoOnly","true");
	        handler.addServlet(publicHolder, public_resources_context + "/*");
        }
        if(api_servlet_class_name != null) {
        	try { handler.addServlet(api_servlet_class_name, "/api/*");} catch (Exception exception) { exception.printStackTrace(); }
        }
        server.setHandler(handler);
        return server;	
	}
