### ISSUE TITLE
DateTime with style SWT.DATE | SWT.DROP_DOWN and minimum and maximum set selects wrong date on drop-down date-picker

### ISSUE THREAD

**Issue by fappel** [eclipse-rap/org.eclipse.rap#253]
**Expected Behavior**
Having a DateTime control with style SWT.DATE | SWT.DROP_DOWN and minimum and maximum set, I would expect that a date selected from the drop-down date-picker within the given minimum and maximum range is always reflected by the DateTime#getYear, DateTime#getMonth, and DateTime#getDay accessors.

**Current Behavior**
On a situation as shown in the picture below, the DateTime control is set to the minimum date instead to the selected date and displays a date below the minimum. 

**Steps to reproduce**
1. [Open the RWT Controls Demo and select the DateTime Control ](https://rap.eclipsesource.com/demo/release/controls/#DateTime)
2. Choose the Type Date, the style DROP_DOWN, and add a Selection Listener
3. Set the minimum date to a day just about a week before the end of the last month 
4. Set the maximum a day in the past (not sure if this is actually necessary)
5. Open the drop-down date picker
6. Choose a date from the last month in the allowed range

The drop-down does not close but switches to the last month, the DateTime control shows a date that is below the lower boundary but is actually set to the lower boundary date. The latter can be seen by the selection event message in the picture below. From this point, the date-picker will accept input, but it will not propagate any changes further to the server.

<img width="1281" alt="Screenshot 2024-12-04 at 04 38 51" src="https://github.com/user-attachments/assets/f5169ce2-b54f-4f22-aab3-6e826d511407">

**Comment by ifurnadjiev** [comment]
I got a JS error here with latest Chrome, when debug is turned on:
```
Error: RangeError: Maximum call stack size exceeded

  Stack: RangeError: Maximum call stack size exceeded
    at Object.func [as setValue] (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:2659:26)
    at Object._applyMin (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:27141:12)
    at Object.func [as setMin] (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:2929:33)
    at Object.setMin (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:26167:32)
    at Object._applyMonthSpinnerValue (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:59772:21)
    at Object.setMonth (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:60158:14)
    at Object._applyLimitRestriction (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:59836:14)
    at Object._onSpinnerChange (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:59827:14)
    at Object._dispatchEvent (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:3855:18)
    at Object.dispatchEvent (http://127.0.0.1:8080/controls/rwt-resources/410/rap-client.js:3796:12)
  Debug: on
```
